# -*- coding: utf-8 -*-
"""Semana 3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jrv7QEanIq3LfepdltMBK6YWgrY2mo5C
"""

import sqlite3

con = sqlite3.connect('tienda.db')

con = sqlite3.connect('tienda.db')

cursorObj = con.cursor()

:memory:

import sqlite3

from sqlite3 import Error

def sql_connection():

    try:

        con = sqlite3.connect(':memory:')

        print("Connection is established: Database is created in memory")

    except Error:

        print(Error)

    finally:

        con.close()

sql_connection()

import sqlite3

from sqlite3 import Error

def sql_connection():

    try:

        con = sqlite3.connect('tienda.db')

        return con

    except Error:

        print(Error)

def sql_table(con):

    cursorObj = con.cursor()

    cursorObj.execute("CREATE TABLE tienda(id integer PRIMARY KEY, nombreproducto text, precio real, stock real, fechallegada text)")

    con.commit()

con = sql_connection()

sql_table(con)

import sqlite3

con = sqlite3.connect('tienda.db')

def sql_insert(con, entities):

    cursorObj = con.cursor()
    
    cursorObj.execute('INSERT INTO tienda(id, nombreproducto, precio, stock, fechallegada) VALUES(?, ?, ?, ?, ?)', entities)
    
    con.commit()

entities = (1, 'kilo-yuca', 5, 20, "14/04/20")

sql_insert(con, entities)

import sqlite3

con = sqlite3.connect('tienda.db')

def sql_insert(con, entities):

    cursorObj = con.cursor()
    
    cursorObj.execute('INSERT INTO tienda(id, nombreproducto, precio, stock, fechallegada) VALUES(?, ?, ?, ?, ?)', entities)
    
    con.commit()

entities = (2, 'kilo-papa', 4, 15, "10/04/20")

sql_insert(con, entities)

import sqlite3

con = sqlite3.connect('tienda.db')

def sql_insert(con, entities):

    cursorObj = con.cursor()
    
    cursorObj.execute('INSERT INTO tienda(id, nombreproducto, precio, stock, fechallegada) VALUES(?, ?, ?, ?, ?)', entities)
    
    con.commit()

entities = (3, 'kilo-azucar', 2.8, 25, "12/04/20")

sql_insert(con, entities)

import sqlite3

con = sqlite3.connect('tienda.db')

def sql_insert(con, entities):

    cursorObj = con.cursor()
    
    cursorObj.execute('INSERT INTO tienda(id, nombreproducto, precio, stock, fechallegada) VALUES(?, ?, ?, ?, ?)', entities)
    
    con.commit()

entities = (4, 'kilo-manzana', 2.5, 10, "11/04/20")

sql_insert(con, entities)

import sqlite3

con = sqlite3.connect('tienda.db')

def sql_insert(con, entities):

    cursorObj = con.cursor()
    
    cursorObj.execute('INSERT INTO tienda(id, nombreproducto, precio, stock, fechallegada) VALUES(?, ?, ?, ?, ?)', entities)
    
    con.commit()

entities = (5, 'kilo-mango', 4.8, 10, "16/04/20")

sql_insert(con, entities)

import sqlite3

con = sqlite3.connect('tienda.db')

def sql_insert(con, entities):

    cursorObj = con.cursor()
    
    cursorObj.execute('INSERT INTO tienda(id, nombreproducto, precio, stock, fechallegada) VALUES(?, ?, ?, ?, ?)', entities)
    
    con.commit()

entities = (6, 'kilo-pera', 2.4, 12, "17/04/20")

sql_insert(con, entities)